name: GCP Docker Deployment

on:
  push:
    branches:
      - private


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
            echo "VM_IP=${{ secrets.DEV_VM_IP }}" >> $GITHUB_ENV
          
      - name: Add SSH Key
        run: |
          echo "${{ secrets.GCP_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to VM via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.VM_SSH_USER }}@$VM_IP << 'EOF'
          ssh ${{ secrets.VM_SSH_USER }}@${{ secrets.PRIVATE_VM_IP }}  << 'INNER'
              cd /home/manish_sharma/app 
              pwd
              echo "hostname -I"
              hostname -I        
              git fetch --all
              git checkout ${{ github.ref_name }}
              git pull origin ${{ github.ref_name }}
              echo "${{ secrets.APP_ENV_FILE }}" > .env
              docker compose down || true
              docker compose up -d --build
            INNER
          EOF
      
