name: GCP Docker Deployment

on:
  push:
    branches:
      - private

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          echo "VM_IP=${{ secrets.DEV_VM_IP }}" >> $GITHUB_ENV
          echo "PRIVATE_IP=${{ secrets.PRIVATE_VM_IP }}" >> $GITHUB_ENV

      - name: Add SSH Key
        run: |
          echo "${{ secrets.GCP_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > keyprivate.pem
          chmod 600 keyprivate.pem

      - name: Deploy to Private VM via Public VM
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.VM_SSH_USER }}@$VM_IP << 'EOF'
            echo "${{ secrets.PRIVATE_SSH_KEY }}" > keyprivate.pem
            chmod 600 keyprivate.pem

            ssh -o StrictHostKeyChecking=no -i keyprivate.pem ${{ secrets.VM_SSH_USER }}@$PRIVATE_IP << 'INNER_EOF'
              set -e
              if [ ! -d "/home/${{ secrets.VM_SSH_USER }}/app" ]; then
                git clone https://github.com/Manish-auriga/backend.git /home/${{ secrets.VM_SSH_USER }}/app
              fi
              cd /home/${{ secrets.VM_SSH_USER }}/app
              git fetch --all
              git checkout ${{ github.ref_name }}
              git pull origin ${{ github.ref_name }}
              echo "${{ secrets.APP_ENV_FILE }}" > .env
              sudo docker compose down || true
              sudo docker compose up -d --build
            INNER_EOF
          EOF

